name:        Paddy Cole
description: UX & Interaction Designer
url:         http://paddycole.com
markdown:    kramdown
highlighter: pygments
permalink:   /project/:title/
exclude:    [
              'gulpfile.js',
              'node_modules',
              'npm-debug.log',
              'package.json'
            ]
defaults:
  -
    scope:
      path:   ""
    values:
      layout: "post"
